/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import EDD.Lista;
import EDD.Vertice;
import Funcionalidades.Funcion;
import static GUI.AgregarEstaciones.nuevosVertices;
import static GUI.CargaDeRed.grafoEDD;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author eabdf
 */
public class ConectarRedConLinea extends javax.swing.JFrame {

    DefaultComboBoxModel modelEstacionesLinea = new DefaultComboBoxModel();
    DefaultComboBoxModel modelEstacionesRed = new DefaultComboBoxModel();
    private Funcion function = new Funcion();

    /**
     * Creates new form ConectarRedConLinea
     */
    public ConectarRedConLinea() {
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);

        this.llenarComboBoxs();
    }

    private void llenarComboBoxs() {
        Lista nombresRed = function.mostrarEstaciones(grafoEDD);
        Lista nombresLinea = function.mostrarListaVertice(nuevosVertices);

        for (int i = 0; i < nombresRed.getSize(); i++) {
            modelEstacionesRed.addElement(nombresRed.getValor(i));
        }

        for (int i = 0; i < nombresLinea.getSize(); i++) {
            modelEstacionesLinea.addElement(nombresLinea.getValor(i));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        estacionesLinea = new javax.swing.JComboBox<>();
        estacionesRed = new javax.swing.JComboBox<>();
        conectarLineaRed = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        estacionesLinea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(estacionesLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        estacionesRed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(estacionesRed, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        conectarLineaRed.setText("jButton1");
        conectarLineaRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conectarLineaRedActionPerformed(evt);
            }
        });
        jPanel1.add(conectarLineaRed, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void conectarLineaRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conectarLineaRedActionPerformed
        for (int i = 0; i < nuevosVertices.getSize(); i++) {
            Vertice verticeActual = (Vertice) nuevosVertices.getValor(i);
            grafoEDD.InsertarVertice(verticeActual);
        }

        String nombre1 = (String) estacionesRed.getSelectedItem();
        String nombre2 = (String) estacionesLinea.getSelectedItem();

        grafoEDD.agregarConexion(nombre1, nombre2);

        MenuPrincipal menuPrincipal = new MenuPrincipal();
        this.dispose();
    }//GEN-LAST:event_conectarLineaRedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConectarRedConLinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConectarRedConLinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConectarRedConLinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConectarRedConLinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConectarRedConLinea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton conectarLineaRed;
    private javax.swing.JComboBox<String> estacionesLinea;
    private javax.swing.JComboBox<String> estacionesRed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
