/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Funcionalidades.Validacion;
import static GUI.CargaDeRed.t;
import javax.swing.JOptionPane;

/**
 *
 * @author eabdf
 */
public class EstablecerValorT extends javax.swing.JFrame {

    /**
     * Creates new form EstablecerValorT
     */
    public EstablecerValorT() {
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inputNuevoValorT = new javax.swing.JTextField();
        cambiar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        valorActual = new javax.swing.JLabel();
        IrMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Establecer valor de T ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel2.setText("Ingresa el valor de T:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));
        jPanel1.add(inputNuevoValorT, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 240, 50));

        cambiar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        cambiar.setText("cambiar");
        cambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarActionPerformed(evt);
            }
        });
        jPanel1.add(cambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel3.setText("Valor actual de T:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        valorActual.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        valorActual.setForeground(new java.awt.Color(0, 0, 255));
        jPanel1.add(valorActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 20, -1));

        IrMenu.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        IrMenu.setText("Ir al menú");
        IrMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IrMenuActionPerformed(evt);
            }
        });
        jPanel1.add(IrMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarActionPerformed
        if (!inputNuevoValorT.getText().isEmpty()) {
            Validacion validacion = new Validacion();
            String nuevaTStr = inputNuevoValorT.getText();
            if (validacion.ValidarNumero(nuevaTStr) != -1) {
                int valorInicialT = validacion.ValidarNumero(nuevaTStr);
                t = valorInicialT;
                JOptionPane.showMessageDialog(null, "El valor de T se actualizo correctamente");
                inputNuevoValorT.setText("");
                valorActual.setText(String.valueOf(t));

            } else {
                JOptionPane.showMessageDialog(null, "Debe ser un numero entero ! ");
            }
        }
    }//GEN-LAST:event_cambiarActionPerformed

    private void IrMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IrMenuActionPerformed
       MenuPrincipal menu = new MenuPrincipal();
       this.dispose();
    }//GEN-LAST:event_IrMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstablecerValorT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstablecerValorT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstablecerValorT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstablecerValorT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstablecerValorT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IrMenu;
    private javax.swing.JButton cambiar;
    private javax.swing.JTextField inputNuevoValorT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel valorActual;
    // End of variables declaration//GEN-END:variables
}
